### Create a payment
POST http://localhost:3000/api/v1/payments
Content-Type: application/json
Idempotency-Key: key-1

{
  "description": "First payment",
  "due_date": "2025-10-20",
  "amount_cents": 1500,
  "currency": "USD",
  "payer": { "name": "Lautaro", "email": "lauta@example.com" }
}


### List payments
GET http://localhost:3000/api/v1/payments


### Create batch
POST http://localhost:3000/api/v1/payments/batch
Content-Type: application/json
Idempotency-Key: batch-1

[
  { "description": "Payment 1", 
    "due_date": "2025-10-25", 
    "amount_cents": 1000, 
    "currency": "USD", 
    "payer": { "name": "Juan", "email": "juan@test.com" } 
    },
    
  { "description": "Payment 2", 
    "due_date": "2025-10-26", 
    "amount_cents": 2000, 
    "currency": "USD", 
    "payer": { "name": "Ana", "email": "ana@test.com" } 
    }
]























### Simular webhook
POST http://localhost:3000/api/v1/webhooks/simulate
Content-Type: application/json
X-Webhook-Token: secret_token

{
  "payment_id": "1145ca12-e287-4928-9de2-9a890ab56497",
  "new_status": "reversed",
  "reason": "Payment reversed"
}
