### Crear un pago
POST http://localhost:3000/api/v1/payments
Content-Type: application/json
Idempotency-Key: key-1

{
  "description": "Servicio de prueba",
  "due_date": "2025-10-20",
  "amount_cents": 1500,
  "currency": "USD",
  "payer": { "name": "Juan", "email": "lauta@example.com" }
}

### Listar pagos
GET http://localhost:3000/api/v1/payments

### Crear batch
POST http://localhost:3000/api/v1/payments/batch
Content-Type: application/json
Idempotency-Key: batch-1

[
  { "description": "Pago 1", "due_date": "2025-10-25", "amount_cents": 1000, "currency": "USD", "payer": { "name": "Juan", "email": "juan@test.com" } },
  { "description": "Pago 2", "due_date": "2025-10-26", "amount_cents": 2000, "currency": "USD", "payer": { "name": "Ana", "email": "ana@test.com" } }
]

### Simular webhook
POST http://localhost:3000/api/v1/webhooks/simulate
Content-Type: application/json
X-Webhook-Token: change_me_secret_token

{
  "payment_id": "6cff401b-13fd-41e1-be6b-0ccea6ca5ed0",
  "new_status": "reversed",
  "reason": "Pago aprobado manualmente"
}
